development:
  adapter: mysql2
  encoding: utf8
  database: bitcoin_central_development
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: bitcoin_central_test
  username: root
  password: 
